[build]
  command = "npm run build"
  publish = ".next"
[build.environment]
  NODE_VERSION = "18"

[dev]
  command = "npm run dev"
  port = 3002
  targetPort = 3002
  framework = "next"

[[plugins]]
  package = "@netlify/plugin-nextjs"